# Generated by Django 2.0.1 on 2018-01-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newraddress', models.CharField(max_length=255)),
            ],
        ),
    ]
