# Generated by Django 2.0.1 on 2018-01-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customdata', '0002_newsurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsurl',
            name='newraddress',
            field=models.TextField(max_length=255),
        ),
    ]
